Add 'pre-runner-script' option
machulav/ec2-github-runner pull request #154
Opened 2023-06-21 23:07 UTC by tonyhutter

Add a `pre-runner-script` option to specify arbitrary bash commands to run before the runner starts up on the instance.  This is useful if you need to install dependencies or have OS-specific setup steps.  For example:
```yaml
          - name: Start EC2 runner
            with:
              mode: start
              ec2-image-id: ami-07bdb09c49774f92e
              pre-runner-script: |
                 sudo yum update -y && \
                 sudo yum install docker git libicu -y && \
                 sudo systemctl enable docker
```

2023-06-22 18:35 UTC, tonyhutter commented
The `lint-code` check has been running for a day.  I'm not sure what's going on with that.

2023-07-06 22:23 UTC, tonyhutter commented
@machulav would you mind taking a look at this?  I have a few more PRs that I want to submit after this one gets in.

2023-07-06 22:54 UTC, machulav requested changes
Hi @tonyhutter,

Thank you for the great idea and your contribution!
I like the idea of the `pre-runner-script` a lot as it may save a lot of time.

I've left a couple of comments on the PR. Please have a look when you have time.

2023-07-06 22:54 UTC, machulav commented on action.yml
> +      Bash commands to run before the actions-runner runs.  This is useful for installing dependencies.
Let's use similar description to the one from the README:

```suggestion
      Specifies bash commands to run before the runner starts. It's useful for installing dependencies with apt-get, yum, dnf, etc.
```

2023-07-06 22:54 UTC, machulav commented on README.md
> +| `pre-runner-script`                                                                                                                                                              | Optional. Used onl
I would simplify the example a bit:

```suggestion
| `pre-runner-script`                                                                                                                                                              | Optional. Used only with the `start` mode. | Specifies bash commands to run before the runner starts.  It's useful for installing dependencies with apt-get, yum, dnf, etc. For example:<pre>          - name: Start EC2 runner<br>            with:<br>              mode: start<br>              ...<br>              pre-runner-script: \|<br>                 sudo yum update -y && \ <br>                 sudo yum install docker git libicu -y<br></pre>
```

In addition, I would ask you to add the missing `sudo systemctl enable docker` line at the very end to duplicate the setup script from above.

2023-07-06 22:54 UTC, machulav commented on README.md
> +```
What if we say like the following, to not give the user the same example two times on the page?

```suggestion
Alternatively, you can use a vanilla EC2 AMI and set up the dependencies via `pre-runner-script` in the workflow YAML file. See example in the `pre-runner-script` documentation below.
```

2023-07-06 23:54 UTC, tonyhutter commented
@machulav thanks for you suggestions.  I've included them all in my latest push.

2023-07-07 08:43 UTC, merged

2023-08-02 11:54 UTC, mickmorse commented
I get this when using pre-runner-script

`Warning: Unexpected input(s) 'pre-runner-script', valid inputs are ['mode', 'github-token', 'ec2-image-id', 'ec2-instance-type', 'subnet-id', 'security-group-id', 'label', 'ec2-instance-id', 'iam-role-name', 'aws-resource-tags', 'runner-home-dir']`

Any reason why? as it is a valid input in actions.yml

2023-08-02 12:27 UTC, mickmorse commented
ah nvm it's not tagged that's why.

2023-08-02 12:28 UTC, mickmorse commented
are we expecting a new tag soon?

2023-10-12 19:29 UTC, wu-json commented
+1 can we get a new tag?

2023-10-24 22:50 UTC, Johannes-Renderheads commented
@machulav any way we can get a new release that includes the pre-runner-script option?

2023-12-03 10:28 UTC, machulav commented
The new tag with this feature is released: [v2.3.4](https://github.com/machulav/ec2-github-runner/releases/tag/v2.3.4).
Also, the major version tag `v2` was updated.

I'm sorry for such a long delays. I don't have much time supporting this project anymore.
Will make an announcement in discussions soon.